export const SERVER_ERROR = "SERVER_ERROR";
export const YUP_ERROR = "YUP_ERROR";
export const INVALID_TRAVEL_DATE = "INVALID_TRAVEL_DATE";
export const INVALID_TRAVEL_DATE_RANGE = "INVALID_TRAVEL_DATE_RANGE";