export const SERVER_ERROR = "SERVER_ERROR";
export const YUP_ERROR = "YUP_ERROR";

// Flights
export const INVALID_TRAVEL_DATE = "INVALID_TRAVEL_DATE";
export const INVALID_TRAVEL_DATE_RANGE = "INVALID_TRAVEL_DATE_RANGE";
export const FLIGHTS_NOT_FOUND = "FLIGHTS_NOT_FOUND";
export const INVALID_FLIGHT_NUMBER = "INVALID_FLIGHT_NUMBER";

// Arcjet
export const TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS";
export const BOTS_DETECTED = "BOTS_DETECTED";
export const ACCESS_DENIED = "ACCESS_DENIED";